---@alias OD.Variant ('dark'|'darker'|'cool'|'deep'|'warm'|'warmer'|'light')
---@alias OD.Diagnostics table<'darker'|'undercurl'|'background', boolean>

---@class OD
---@field style? OD.Variant
---@field transparent? boolean
---@field term_colors? boolean
---@field ending_tildes? boolean
---@field cmp_itemkind_reverse? boolean
---@field toggle_style_key? nil|string
---@field toggle_style_list? string[]
---@field code_style? table<string, string>
---@field lualine? table
---@field colors? table
---@field highlights? table
---@field diagnostics? OD.Diagnostics

--- A loadable color schemes table.
---
--- ## Description
--- Each colorscheme is a table with **three** items:
--- * `mod_pfx`: A **protected** string for internal calls
--- * `mod_cmd`: A **protected** string to pass to `vim.cmd`. It **MUST** look like `'colorscheme ...'`.
--- * `setup`: A function to setup and set the colorscheme.
---
--- If the colorscheme is not a lua plugin, use `vim.g` as a check instead.
---@class CscSubMod
---@field setup? fun(self: CscSubMod, variant: string?, transparent: boolean?, override: table?)
---@field variants? string[]
---@field mod_cmd string
---@field new? fun(): CscSubMod

--- A loadable color schemes table.
---
--- ## Description
--- Each colorscheme is a table with **three** items:
--- * `mod_pfx`: A **protected** string for internal calls
--- * `mod_cmd`: A **protected** string to pass to `vim.cmd`. It **MUST** look like `'colorscheme ...'`.
--- * `setup`: A function to setup and set the colorscheme.
---
--- If the colorscheme is not a lua plugin, use `vim.g` as a check instead.
---@class ODSubMod: CscSubMod
---@field setup? fun(self: CscSubMod, variant: OD.Variant, transparent: boolean?, override: OD?)
---@field new fun(): ODSubMod

--- A table for each **explicitly** configured colorscheme.
---
--- ## Description
--- The colorschemes must comply with the `CscSubMod` type specifications.
---
---@class CscMod
---@field catppuccin? CscSubMod
---@field dracula? CscSubMod
---@field gloombuddy? CscSubMod
---@field gruvbox? CscSubMod
---@field kanagawa? CscSubMod
---@field molokai? CscSubMod
---@field nightfox? CscSubMod
---@field oak? CscSubMod
---@field onedark? ODSubMod
---@field space_vim_dark? CscSubMod
---@field spaceduck? CscSubMod
---@field spacemacs? CscSubMod
---@field tokyonight? CscSubMod
---@field new fun(): CscMod

--- vim:ts=4:sts=4:sw=4:et:ai:si:sta:ci:pi:confirm:fenc=utf-8:noignorecase:smartcase:ru:
