indent_type = "Tabs"
indent_width = 4
column_width = 120
line_endings = "Unix"
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
