indent_type = "Spaces"
indent_width = 4
column_width = 100
line_endings = "Unix"
quote_style = "AutoPreferSingle"
call_parentheses = "Always"
collapse_simple_statement = "FunctionOnly"

[sort_requires]
enabled = false
