[formatting]
align_comments        = true
align_entries         = true
align_single_comments = true
allowed_blank_lines   = 1
array_auto_expand     = true
array_trailing_comma  = true
column_width          = 100
compact_entries       = false
crlf                  = false
indent_entries        = false
indent_tables         = true
reorder_arrays        = true
reorder_keys          = true
