---@module 'lazy'

local colorscheme_init = require('config.util').colorscheme_init
local in_console = require('user_api.check').in_console

---@type LazySpec[]
return {
    {
        'folke/tokyonight.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_tokyonight'),
        cond = not in_console(),
    },
    {
        'embark-theme/vim',
        dev = true,
        lazy = false,
        priority = 1000,
        name = 'embark',
        version = false,
        init = colorscheme_init('installed_embark'),
        cond = not in_console(),
    },
    {
        'jim-at-jibba/ariake.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_ariake'),
        cond = not in_console(),
    },
    {
        'tiagovla/tokyodark.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_tokyodark'),
        cond = not in_console(),
    },
    {
        'darianmorat/gruvdark.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_gruvdark'),
        cond = not in_console(),
    },
    {
        'catppuccin/nvim',
        lazy = false,
        name = 'catppuccin',
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_catppuccin'),
        cond = not in_console(),
    },
    {
        'navarasu/onedark.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_onedark'),
        cond = not in_console(),
    },
    {
        'EdenEast/nightfox.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_nightfox'),
        cond = not in_console(),
    },
    {
        'rebelot/kanagawa.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_kanagawa'),
        cond = not in_console(),
    },
    {
        'vague-theme/vague.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_vague'),
        cond = not in_console(),
    },
    {
        'thesimonho/kanagawa-paper.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_kanagawa_paper'),
        cond = not in_console(),
    },
    {
        'Mofiqul/vscode.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_vscode'),
        cond = not in_console(),
    },
    {
        'Mofiqul/dracula.nvim',
        lazy = false,
        name = 'dracula',
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_dracula'),
        cond = not in_console(),
    },
    {
        'ellisonleao/gruvbox.nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_gruvbox'),
        cond = not in_console(),
    },
    {
        'kepano/flexoki-neovim',
        lazy = false,
        name = 'flexoki',
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_flexoki'),
        cond = not in_console(),
    },
    {
        'bkegley/gloombuddy',
        lazy = false,
        priority = 1000,
        version = false,
        dependencies = {
            {
                'tjdevries/colorbuddy.vim',
                lazy = false,
                priority = 1000,
                version = false,
                init = colorscheme_init('installed_colorbuddy'),
                cond = not in_console(),
            },
        },
        init = colorscheme_init('installed_gloombuddy'),
        cond = not in_console(),
    },
    {
        'vigoux/oak',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init({ installed_oak = 1, oak_virtualtext_bg = 1 }),
    },
    {
        'pineapplegiant/spaceduck',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_spaceduck'),
        cond = not in_console(),
    },
    {
        'liuchengxu/space-vim-dark',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_space_vim_dark'),
        cond = not in_console(),
    },
    {
        'tomasr/molokai',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_molokai'),
    },
    {
        'Th3Whit3Wolf/space-nvim',
        lazy = false,
        priority = 1000,
        version = false,
        init = colorscheme_init('installed_space_nvim'),
        cond = not in_console(),
    },
}
--- vim:ts=4:sts=4:sw=4:et:ai:si:sta:
