---@meta

---@module 'which-key'

-- The Vim modes used for `which-key` as a `string`
---@alias RegModes
---|'n'
---|'i'
---|'v'
---|'t'
---|'o'
---|'x'

--- This is an abstraction of `vim.keymaps.set.Opts` (see `User.Maps.Kmap`), with few extensions
--- ---
--- ## Description
---
--- This table defines a keymap that is used for grouping keymaps with an extra sequence,
--- e.g.
---
--- This class type is reserved for either direct usage with `which-key`, or most regularly
--- for `User.maps.map_dict()` and anything in the `User.maps.wk` module
---
--- ---
---@see vim.keymap.set.Opts
---@see User.Maps.WK
---@see RegModes
---@class RegKey: vim.keymap.set.Opts
--- AKA `lhs` of a Vim Keymap
---@field [1] string
--- AKA `rhs` of a Vim Keymap
---@field [2] string|fun()
--- Keymap's description
---@field desc? string
--- If `true`, `which-key` will hide this keymap
--- **See `:h vim.keymap.set()` to find the other fields**
---@field hidden? boolean
--- Any of the Vim modes: `'n'|'i'|'v'|'t'|'o'|'x'`
---@field mode? RegModes

--- A **group mapping scheme** for usage related to `which-key`
--- ---
--- ## Description
---
---  * **WARNING:** If you remove the `group` field, it'll be parsed as any other table
---
--- This class type is reserver for either direct usage with `which-key`, or most regularly
--- for `User.maps.map_dict()` and anything in the `User.maps.wk` module
---
--- This table defines a keymap that is used for grouping keymaps with an extra sequence,
--- e.g.
---
--- ```
--- <leader>fs    <=== [ ] not a group
--- <leader>f     <=== [X] this is a group the keymap above belongs to
--- ```
---
--- **_EXAMPLE:_**
---
--- ```lua
--- arbitrory_keys = {
---     ['<leader><leader>']= { group = '+Group1', buffer = 4, hidden = true },
---                         --- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
---                             --- This is the `RegPfx` table
--- }
--- ```
---
--- ---
--- ## Fields
---
--- - **_`group`_** (string): The name of the group. Optionally you can prepend a `+` to the name, but
---                   I don't think `which-key` cares if you don't do it
---
--- - **_`hidden`_** (boolean, **optional**): Determines whether said key should be shown by `which-key` or not
---
--- **See `:h vim.keymap.set()` to find the other fields**
---
--- ---
---@see vim.keymap.set.Opts
---@see User.Maps.WK
---@class RegPfx: vim.keymap.set.Opts
---@field group string
---@field hidden? boolean
---@field mode? MapModes

--- A dictionary of string ==> `RegKey` class
--- ---
--- ## Description
---
--- This merely describes a dictionary of `RegKey` type objects
---
--- **Example:**
---
--- ```lua
--- -- DO NOT COPY THE CODE BELOW OUT OF THE BLUE!!!!
---
--- ---@type RegKeys
--- local Keys = {
---     ['<leader>x'] = {
---         rhs()|'rhs',
---         { ... }, ---@see vim.keymap.set.Opts
---         hidden = false,
---         mode = 'n' | 'i' | 'v' | 't' | 'o' | 'x',
---     },
--- }
--- ```
--- @see RegKey
---@alias RegKeys table<string, RegKey>

--- @see RegPfx
--- A dictionary of string ==> `RegPfx` class
--- ---
--- ## Description
---
--- This merely describes a dictionary of `RegPfx` type objects
---
--- - **NOTE:** This is **only valid if** _`which-key`_ is installed
---@alias RegKeysNamed table<string, RegPfx>

---@alias ModeRegKeys table<MapModes, RegKeys>

---@alias ModeRegKeysNamed table<MapModes, RegKeysNamed>

---@class RegKeyOpts: vim.keymap.set.Opts
---@field mode? MapModes
---@field hidden? boolean
---@field group? string

--- Configuration table to be passed to `require('which-key').add()`
--- ---
---@see wk.Opts
---@class RegOpts: wk.Opts
---@field create? boolean
---@field notify? boolean
---@field version? number

--- vim:ts=4:sts=4:sw=4:et:ai:si:sta:noci:nopi:
