name: Action Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  merge_group:
    branches:
      - main
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build project assets
        id: checkout
        run: |
          mkdir -pv Jnvim
          cp init.lua lua README.md LICENSE Pipfile requirements.txt Jnvim
          zip -r -9 Jnvim.zip Jnvim
          tar cvJf Jnvim.tar.xz Jnvim
          sha512sum Jnvim.zip >| Jnvim.zip.sha512sum
          sha512sum Jnvim.tar.xz >| Jnvim.tar.xz.sha512sum
          rm -rfv Jnvim

      - name: Get Release
        id: get_current_release
        uses: joutvhu/get-release@v1.0.3
        with:
          # Should get latest release?
          latest: true
          # Find the latest release including the pre-releases
          prerelease: true
          # A pattern string to filter the releases by tag_name
          pattern: '^v.*'
          # Show ouputs
          debug: true
          # Fail when no release was found
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release File
        run: echo ${{ github.sha }} >| Release.txt
      - name: Test Release
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            Jnvim.tar.xz
            Jnvim.tar.xz.sha512sum
            Jnvim.zip
            Jnvim.zip.sha512sum
          token: ${{ secrets.GITHUB_TOKEN }}

