name: Luacheck

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

env:
  CLICOLOR: 1

jobs:
  luacheck:
    name: Lint Lua files using Luacheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: .
